# Populate Consul with Data
consul kv put "$1/address" "1234 Seaseme Street, Somewhere, CA. 12345"
consul kv put "$1/email" "someone@mydomain.com"
consul kv put "$1/phone" "123-456-7890"
consul kv put "$1/profile_summary" "Looking to work with modern technologies!"

consul kv put "$1/org/0/name" "Some Company, Inc."
consul kv put "$1/org/0/position/0/name" "CloudOps Engineer"
consul kv put "$1/org/0/position/0/tasks/0" "I did a lot of things while working here."
consul kv put "$1/org/0/position/0/tasks/1" "I guess you could say the more time I spent there, the more I accomplished ."
consul kv put "$1/org/0/position/0/tasks/2" "I was fairly productive most of the time."
consul kv put "$1/org/0/position/1/name" "Sr. CloudOps Engineer"
consul kv put "$1/org/0/position/1/tasks/0" "I continued to do more things."
consul kv put "$1/org/0/position/1/tasks/1" "Seemed like I was there forever."
consul kv put "$1/org/0/position/1/tasks/2" "I may have over stayed my welcome."
consul kv put "$1/org/0/position/2/name" "Principal Cloud Engineer"
consul kv put "$1/org/0/position/2/tasks/0" "I continued to be a badass and do more."
consul kv put "$1/org/0/position/2/tasks/1" "I really needed a vacation."
consul kv put "$1/org/0/position/2/tasks/2" "Not to mention a bonus wouldn't hurt."

consul kv put "$1/org/1/name" "Another Company, Inc."
consul kv put "$1/org/1/position/0/name" "DevOps Engineer"
consul kv put "$1/org/1/position/0/tasks/0" "I did a bunch of things."
consul kv put "$1/org/1/position/0/tasks/1" "I wouldn't exactly call it devops."
consul kv put "$1/org/1/position/0/tasks/2" "They had me doing all sorts of janitoral tasks."
consul kv put "$1/org/1/position/1/name" "Sr. DevOps Engineer"
consul kv put "$1/org/1/position/1/tasks/0" "I found some fun stuff to work on."
consul kv put "$1/org/1/position/1/tasks/1" "Also found a group of people I enjoyed."
consul kv put "$1/org/1/position/1/tasks/2" "I kicked ass and impressed a few people."
consul kv put "$1/org/1/position/2/name" "Principal Software Engineer"
consul kv put "$1/org/1/position/2/tasks/0" "I eventually found what I really liked doing."
consul kv put "$1/org/1/position/2/tasks/1" "I couldn't get enough of it."
consul kv put "$1/org/1/position/2/tasks/2" "ADIDAScripts."
